[project]
name = "web-01-10-hw"
version = "0.1.0"
description = ""
authors = [
    {name = "Vitalii Stepanets",email = "vetal8421@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.4,<7.0.0)",
    "pymongo (>=4.16.0,<5.0.0)",
    "utils (>=1.0.2,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
