# Generated by Django 6.0.4 on 2026-05-03 22:51

import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_fullname',
            field=models.CharField(max_length=100, validators=[quotes.models.existing_author]),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quotes.tag'),
        ),
    ]
